name: Test Submissions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install pytest

      - name: List directory contents for debugging
        run: ls -R

      - name: Clean cache
        run: |
          rm -rf .pytest_cache
          rm -rf problems/**/__pycache__

      - name: Run tests
        run: pytest problems/**/tests.py --maxfail=1 --disable-warnings || exit 1
